window.addEventListener('load',()=>{setTimeout(()=>{const loader=document.getElementById('loader');if(loader){loader.classList.add('hidden');setTimeout(()=>{loader.style.display='none'},700)}triggerReveal()},1900)});
const cursor=document.getElementById('cursor');const cursorFollower=document.getElementById('cursorFollower');let mouseX=0,mouseY=0,followerX=0,followerY=0;
document.addEventListener('mousemove',(e)=>{mouseX=e.clientX;mouseY=e.clientY;if(cursor){cursor.style.left=mouseX+'px';cursor.style.top=mouseY+'px'}});
function animateCursor(){followerX+=(mouseX-followerX)*0.1;followerY+=(mouseY-followerY)*0.1;if(cursorFollower){cursorFollower.style.left=followerX+'px';cursorFollower.style.top=followerY+'px'}requestAnimationFrame(animateCursor)}animateCursor();
document.querySelectorAll('a,button,.feature-card,.course-card').forEach(el=>{el.addEventListener('mouseenter',()=>{if(cursor)cursor.style.transform='translate(-50%,-50%) scale(2)';if(cursorFollower){cursorFollower.style.transform='translate(-50%,-50%) scale(1.5)';cursorFollower.style.opacity='0.3'}});el.addEventListener('mouseleave',()=>{if(cursor)cursor.style.transform='translate(-50%,-50%) scale(1)';if(cursorFollower){cursorFollower.style.transform='translate(-50%,-50%) scale(1)';cursorFollower.style.opacity='0.6'}})});
const navbar=document.getElementById('navbar');window.addEventListener('scroll',()=>{if(navbar)navbar.classList.toggle('scrolled',window.scrollY>60)});
const hamburger=document.getElementById('hamburger');const mobileMenu=document.getElementById('mobileMenu');if(hamburger&&mobileMenu){hamburger.addEventListener('click',()=>{mobileMenu.classList.toggle('open');const spans=hamburger.querySelectorAll('span');if(mobileMenu.classList.contains('open')){spans[0].style.transform='rotate(45deg) translate(5px,5px)';spans[1].style.opacity='0';spans[2].style.transform='rotate(-45deg) translate(5px,-5px)'}else{spans[0].style.transform='';spans[1].style.opacity='';spans[2].style.transform=''}});document.addEventListener('click',(e)=>{if(!hamburger.contains(e.target)&&!mobileMenu.contains(e.target)){mobileMenu.classList.remove('open')}})}
function triggerReveal(){const revealElements=document.querySelectorAll('.reveal');const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){setTimeout(()=>{entry.target.classList.add('visible')},100);observer.unobserve(entry.target)}})},{threshold:0.12,rootMargin:'0px 0px -50px 0px'});revealElements.forEach(el=>observer.observe(el))}
document.addEventListener('DOMContentLoaded',triggerReveal);
function animateCounters(){const counters=document.querySelectorAll('.stat-num');counters.forEach(counter=>{const target=parseInt(counter.getAttribute('data-target'));const duration=2000;const start=performance.now();function update(time){const elapsed=time-start;const progress=Math.min(elapsed/duration,1);const eased=1-Math.pow(1-progress,3);counter.textContent=Math.round(eased*target);if(progress<1)requestAnimationFrame(update);else counter.textContent=target}requestAnimationFrame(update)})}
const statsSection=document.querySelector('.hero-stats');if(statsSection){const statsObserver=new IntersectionObserver((entries)=>{if(entries[0].isIntersecting){animateCounters();statsObserver.disconnect()}},{threshold:0.5});statsObserver.observe(statsSection)}
function createSakura(){const container=document.getElementById('sakuraContainer');if(!container)return;const symbols=['🌸','🌺','✿','❀'];for(let i=0;i<18;i++){const petal=document.createElement('div');petal.classList.add('sakura');petal.textContent=symbols[Math.floor(Math.random()*symbols.length)];petal.style.left=Math.random()*100+'%';petal.style.fontSize=(12+Math.random()*16)+'px';petal.style.animationDuration=(6+Math.random()*8)+'s';petal.style.animationDelay=(-Math.random()*10)+'s';petal.style.opacity=0.1+Math.random()*0.25;container.appendChild(petal)}}createSakura();
const filterBtns=document.querySelectorAll('.filter-btn');const courseCards=document.querySelectorAll('.course-full-card');filterBtns.forEach(btn=>{btn.addEventListener('click',()=>{filterBtns.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.getAttribute('data-filter');courseCards.forEach(card=>{if(filter==='all'||card.getAttribute('data-level')===filter){card.style.display=''}else{card.style.display='none'}})})});
const contactForm=document.getElementById('contactForm');if(contactForm){contactForm.addEventListener('submit',function(e){e.preventDefault();const btn=contactForm.querySelector('.submit-btn');btn.textContent='Sending...';btn.disabled=true;setTimeout(()=>{btn.textContent='Message Sent!';btn.style.background='#27AE60';contactForm.reset();setTimeout(()=>{btn.textContent='Send Message';btn.style.background='';btn.disabled=false},3000)},1500)})}
window.addEventListener('scroll',()=>{const scrollY=window.scrollY;const hero=document.querySelector('.hero-content');if(hero&&scrollY<window.innerHeight){hero.style.transform='translateY('+scrollY*0.3+'px)';hero.style.opacity=1-scrollY/600}});
